image: atlassian/default-image:3

definitions:
  steps:
    - step: &spectra-code
        name: 'Spectra'
        script:
          - echo "Spectra runs here"
  services:
    docker:
      memory: 4096

options:
  docker: true
  size: 2x

pipelines:
  # Here the system will run the deployment to the AWS S3 
  #for each one of the main branches
  branches:
    development:
      - step: *spectra-code
      - step: 
          name: "GCR Deploy And Systems On Premises"
          image: google/cloud-sdk:latest
          script:
            # Start the Deploy to GCP
            - echo ${GCLOUD_API_KEYFILE} > .gcloud-api-key-prd.json
            - gcloud auth activate-service-account --key-file .gcloud-api-key-prd.json
            - gcloud config set project ${GCP_PROJECT}
            - gcloud auth configure-docker -q
            - docker build -t ${IMAGE_NAME}-dev .
            - docker tag ${IMAGE_NAME}-dev gcr.io/${GCP_PROJECT}/taxly-images/admin/dev/${IMAGE_NAME}
            - docker push gcr.io/${GCP_PROJECT}/taxly-images/admin/dev/${IMAGE_NAME}
          services:
            - docker
          size: 2x
    master:
      - step: *spectra-code
      - step: 
          name: "GCR Deploy And Systems On Premises"
          image: google/cloud-sdk:latest
          script:
            # Start the Deploy to GCP
            - echo ${GCLOUD_API_KEYFILE} > .gcloud-api-key-prd.json
            - gcloud auth activate-service-account --key-file .gcloud-api-key-prd.json
            - gcloud config set project ${GCP_PROJECT}
            - gcloud auth configure-docker -q
            - docker build -f Dockerfile.Prod -t ${IMAGE_NAME}-prod .
            - docker tag ${IMAGE_NAME}-prod gcr.io/${GCP_PROJECT}/taxly-images/admin/prod/${IMAGE_NAME}
            - docker push gcr.io/${GCP_PROJECT}/taxly-images/admin/prod/${IMAGE_NAME}
          services:
            - docker
          size: 2x
